apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: huly
commonLabels:
  app.kubernetes.io/part-of: huly
resources:
  - front-deployment.yaml
  - front-service.yaml
  - account-deployment.yaml
  - account-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - ingress.yaml


